version: '3.6'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - /tmp/postgres:/data/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

  order-service:
    build:
      context: ..
      dockerfile: Dockerfile
    image: local/order-service
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - "SPRING_PROFILES_ACTIVE=OVERRIDES"
    links:
      - postgres
